# Generated by Django 2.2.2 on 2020-09-10 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ImageField(default=datetime.datetime(2020, 9, 10, 9, 0, 34, 384168, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
