# Generated by Django 3.1 on 2020-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200917_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.ImageField(upload_to='images'),
        ),
    ]
