# Generated by Django 3.1 on 2020-09-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskowner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Kiosk',
        ),
        migrations.DeleteModel(
            name='KioskOwner',
        ),
    ]
