# Generated by Django 3.1 on 2020-09-17 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosks', '0003_kiosk_kioskowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosks.kioskowner'),
        ),
        migrations.AddField(
            model_name='kioskowner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
